In [1]:
import yfinance as yf
import pandas as pd

from src import functions as f

%load_ext autoreload
%autoreload 2

In [2]:
f.load_tables('tsm')

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
1997-10-09 00:00:00-04:00,5.646040,6.562691,5.646040,6.323565,3.181335,10201979,0.0,0.0
1997-10-10 00:00:00-04:00,7.014374,7.040944,6.363419,6.615830,3.328370,10669148,0.0,0.0
1997-10-13 00:00:00-04:00,6.629115,6.629115,6.443128,6.469698,3.254853,3044363,0.0,0.0
1997-10-14 00:00:00-04:00,6.416558,6.429843,6.031299,6.204002,3.121182,2549907,0.0,0.0
1997-10-15 00:00:00-04:00,5.818742,6.044584,5.805458,6.031299,3.034299,3167153,0.0,0.0
...,...,...,...,...,...,...,...,...
2025-01-14 00:00:00-05:00,205.190002,206.259995,198.500000,201.449997,201.449997,14182900,0.0,0.0
2025-01-15 00:00:00-05:00,202.490005,209.039993,199.350006,206.800003,206.800003,18286500,0.0,0.0
2025-01-16 00:00:00-05:00,218.889999,221.949997,213.169998,214.789993,214.789993,38539600,0.0,0.0
2025-01-17 00:00:00-05:00,215.169998,215.679993,211.059998,211.500000,211.500000,21559000,0.0,0.0
2025-01-21 00:00:00-05:00,214.460007,220.149994,212.050003,218.699997,218.699997,17125226,0.0,0.0

In [3]:
nvda_raw, last_day, nvda_df=f.transform_table(f.load_tables('tsm'))
nvda_df

,Close,std_23days,z_23days,target,mu_23days,month,dow,pct_top_wick,pct_body,pct_bottom_wick,pct_gap_up_down,z_top_30days,z_body_30days,z_bottom_30days,z_gap_30days
Date,,,,,,,,,,,,,,,
1997-11-20 00:00:00-05:00,4.437123,0.434144,-0.478958,2,4.645059,11,3,0.714284,0.142861,0.142856,-0.700006,2.343500,-1.787962,-0.203633,-0.442175
1997-11-21 00:00:00-05:00,4.662965,0.406946,0.116387,1,4.615602,11,4,0.000000,1.000000,0.000000,0.285722,-0.736417,1.191995,-0.852275,0.548158
1997-11-24 00:00:00-05:00,4.556686,0.406514,-0.127879,2,4.608670,11,0,0.100003,0.899997,0.000000,-1.133337,-0.322581,0.835701,-0.818939,-0.816143
1997-11-25 00:00:00-05:00,4.676250,0.404982,0.141198,1,4.619067,11,1,0.416665,0.583335,0.000000,0.200001,0.985892,-0.268380,-0.763896,0.477965
1997-11-26 00:00:00-05:00,4.596541,0.394538,-0.101015,2,4.636395,11,2,0.142862,0.285709,0.571429,-0.333338,-0.203405,-1.213347,1.890600,-0.065904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-14 00:00:00-05:00,201.449997,6.689995,-0.078703,2,201.976523,1,1,0.137886,0.481960,0.380155,1.081923,-0.613216,-0.107521,0.673187,1.448982
2025-01-15 00:00:00-05:00,206.800003,6.387368,0.654009,2,202.622610,1,2,0.231165,0.444789,0.324046,0.134022,-0.066984,-0.226180,0.367653,-0.044855
2025-01-16 00:00:00-05:00,214.789993,6.617903,1.705912,1,203.500435,1,3,0.348519,0.466971,0.184510,1.247679,0.552014,-0.111660,-0.327890,1.632588
2025-01-17 00:00:00-05:00,211.500000,6.270733,1.136751,2,204.371739,1,4,0.110389,0.794373,0.095239,0.043281,-0.816181,1.072697,-0.752085,-0.214186
2025-01-21 00:00:00-05:00,218.699997,6.893054,1.966945,2,205.141739,1,1,0.179012,0.523456,0.297532,0.640695,-0.380924,0.058479,0.241430,0.669538

In [4]:
last_day

Close              218.699997
std_23days           6.893054
z_23days             1.966945
target               2.000000
mu_23days          205.141739
month                1.000000
dow                  1.000000
pct_top_wick         0.179012
pct_body             0.523456
pct_bottom_wick      0.297532
pct_gap_up_down      0.640695
z_top_30days        -0.380924
z_body_30days        0.058479
z_bottom_30days      0.241430
z_gap_30days         0.669538
Name: 2025-01-21 00:00:00-05:00, dtype: float64

In [5]:
report, model, importances = f.train_test_model(nvda_df)
report

/Users/armanichoy/Documents/stock_project/myenv/lib/python3.12/site-packages/xgboost/core.py:158: UserWarning: [14:50:28] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

Accuracy: 0.38
Classification Report:               precision    recall  f1-score   support

           0       0.38      0.36      0.37       584
           1       0.37      0.39      0.38       712
           2       0.38      0.38      0.38       754

    accuracy                           0.38      2050
   macro avg       0.38      0.37      0.37      2050
weighted avg       0.38      0.38      0.38      2050

In [6]:
importances

array([0.07509989, 0.07330181, 0.07201274, 0.08438728, 0.06626642,
       0.06433403, 0.06739803, 0.07166193, 0.07037644, 0.06485055,
       0.07279305, 0.07691936, 0.07047725, 0.07012116], dtype=float32)

In [7]:
nvda_df['target'].value_counts()

target
2    2454
1    2391
0    1988
Name: count, dtype: int64

In [8]:
last_day_ = last_day.drop(['target'])
last_day_

Close              218.699997
std_23days           6.893054
z_23days             1.966945
mu_23days          205.141739
month                1.000000
dow                  1.000000
pct_top_wick         0.179012
pct_body             0.523456
pct_bottom_wick      0.297532
pct_gap_up_down      0.640695
z_top_30days        -0.380924
z_body_30days        0.058479
z_bottom_30days      0.241430
z_gap_30days         0.669538
Name: 2025-01-21 00:00:00-05:00, dtype: float64

In [9]:
last_day_df = last_day_.to_frame().T
model.predict(last_day_df)[0]

2

In [10]:
model.predict_proba(last_day_df)[0][2]

0.8003921

In [11]:
nvda_df

,Close,std_23days,z_23days,target,mu_23days,month,dow,pct_top_wick,pct_body,pct_bottom_wick,pct_gap_up_down,z_top_30days,z_body_30days,z_bottom_30days,z_gap_30days
Date,,,,,,,,,,,,,,,
1997-11-20 00:00:00-05:00,4.437123,0.434144,-0.478958,2,4.645059,11,3,0.714284,0.142861,0.142856,-0.700006,2.343500,-1.787962,-0.203633,-0.442175
1997-11-21 00:00:00-05:00,4.662965,0.406946,0.116387,1,4.615602,11,4,0.000000,1.000000,0.000000,0.285722,-0.736417,1.191995,-0.852275,0.548158
1997-11-24 00:00:00-05:00,4.556686,0.406514,-0.127879,2,4.608670,11,0,0.100003,0.899997,0.000000,-1.133337,-0.322581,0.835701,-0.818939,-0.816143
1997-11-25 00:00:00-05:00,4.676250,0.404982,0.141198,1,4.619067,11,1,0.416665,0.583335,0.000000,0.200001,0.985892,-0.268380,-0.763896,0.477965
1997-11-26 00:00:00-05:00,4.596541,0.394538,-0.101015,2,4.636395,11,2,0.142862,0.285709,0.571429,-0.333338,-0.203405,-1.213347,1.890600,-0.065904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-14 00:00:00-05:00,201.449997,6.689995,-0.078703,2,201.976523,1,1,0.137886,0.481960,0.380155,1.081923,-0.613216,-0.107521,0.673187,1.448982
2025-01-15 00:00:00-05:00,206.800003,6.387368,0.654009,2,202.622610,1,2,0.231165,0.444789,0.324046,0.134022,-0.066984,-0.226180,0.367653,-0.044855
2025-01-16 00:00:00-05:00,214.789993,6.617903,1.705912,1,203.500435,1,3,0.348519,0.466971,0.184510,1.247679,0.552014,-0.111660,-0.327890,1.632588
2025-01-17 00:00:00-05:00,211.500000,6.270733,1.136751,2,204.371739,1,4,0.110389,0.794373,0.095239,0.043281,-0.816181,1.072697,-0.752085,-0.214186
2025-01-21 00:00:00-05:00,218.699997,6.893054,1.966945,2,205.141739,1,1,0.179012,0.523456,0.297532,0.640695,-0.380924,0.058479,0.241430,0.669538

In [12]:
nvda_raw

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
1997-10-09 00:00:00-04:00,5.646040,6.562691,5.646040,6.323565,3.181333,10201979,0.0,0.0
1997-10-10 00:00:00-04:00,7.014374,7.040944,6.363419,6.615830,3.328371,10669148,0.0,0.0
1997-10-13 00:00:00-04:00,6.629115,6.629115,6.443128,6.469698,3.254853,3044363,0.0,0.0
1997-10-14 00:00:00-04:00,6.416558,6.429843,6.031299,6.204002,3.121183,2549907,0.0,0.0
1997-10-15 00:00:00-04:00,5.818742,6.044584,5.805458,6.031299,3.034297,3167153,0.0,0.0
...,...,...,...,...,...,...,...,...
2025-01-14 00:00:00-05:00,205.190002,206.259995,198.500000,201.449997,201.449997,14182900,0.0,0.0
2025-01-15 00:00:00-05:00,202.490005,209.039993,199.350006,206.800003,206.800003,18286500,0.0,0.0
2025-01-16 00:00:00-05:00,218.889999,221.949997,213.169998,214.789993,214.789993,38539600,0.0,0.0
2025-01-17 00:00:00-05:00,215.169998,215.679993,211.059998,211.500000,211.500000,21559000,0.0,0.0
2025-01-21 00:00:00-05:00,214.460007,220.149994,212.050003,218.699997,218.699997,17125226,0.0,0.0